bearer_token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyOjY0MjU5ZGZlZmQ2N2YzM2I1MTI4YzhmMCIsImV4cCI6MTc4MTU1NzI1NCwiaXNzdWVfYXQiOjE3ODE1MTQwNTQsImF1dGhlbl9pbmZvcyI6eyJTbXNPdHAiOjE3ODE2MDA0ODYsIlVzZXJuYW1lUGFzc3dvcmQiOjE3ODE1NTcyNTR9LCJyb2xlcyI6WyJhZG1pbiJdLCJhdXRoZW50aWNhdGlvbl9kb25lIjp0cnVlLCJkb21haW5faWQiOiJkZWZhdWx0IiwibWV0YV9kYXRhIjp7IkxvZ2luU2Vzc2lvbklkIjoiXCIzcm1EeXA0Qk5xdlpCWElNcUI4NFwiIiwiVXNlckluZm8iOiJ7XCJkb21haW5faWRcIjpcImRlZmF1bHRcIixcInVzZXJfaWRcIjpcIjY0MjU5ZGZlZmQ2N2YzM2I1MTI4YzhmMFwiLFwiZGlzcGxheV9uYW1lXCI6XCLEkOG7lyBNaW5oIFRow7RuZ1wiLFwiZW1haWxcIjpcInRob25nZG00QHZpZXR0ZWwuY29tLnZuXCIsXCJwaG9uZV9udW1iZXJcIjpcIis4NDM1ODA4MjY0NlwiLFwicm9sZXNcIjpbXCJhZG1pblwiXSxcIm93bmVyX2luZm9cIjp7XCJpZGVudGl0eV92ZXJzaW9uXCI6OTU2NDMsXCJ1cGRhdGVkX3RpbWVcIjoxNzcwMjg3NTg1fSxcImF0dHJpYnV0ZXNcIjp7XCJYLU11bHRpLUdhdGV3YXktSW5zdGFuY2UtRW5hYmxlZFwiOlwiZmFsc2VcIixcImxhc3RfbG9naW5fdGltZVwiOlwiMTc4MTUxNDAzMlwifSxcIm1ldGFcIjp7XCJwcm92aWRlclwiOlwiVmlldHRlbCBTU09cIn19In19.xL2ypvKwru2JctG-g8gB1iBNPJky6UuGNEpcBbHKYHI"
admin_user_id = "64259dfefd67f33b5128c8f0"
admin_portal_address = "10.254.148.112:9443"
worker_count = 16
organizational_unit_id = "64620f8bd9c393f77c1ac691"
dry_run = false

# Optional: list of user emails whose enrollment requests should NOT be deleted
exclude_emails = ["tuhv3@viettel.com.vn",
"sonvv@viettel.com.vn",
"tanpv8@viettel.com.vn",
"truongnx191@viettel.com.vn",
"tuanvq5@viettel.com.vn",
"dungnd18@viettel.com.vn",
"hoabv@viettel.com.vn",
"hiennd9@viettel.com.vn",
"thaint@viettel.com.vn",
"congnh2@viettel.com.vn",
"hieuvt@viettel.com.vn",
"vuva@viettel.com.vn",
"dungpq@viettel.com.vn",
"chivd@viettel.com.vn",
"namnt321@viettel.com.vn",
"tiendm@viettel.com.vn",
"thanhvn1@viettel.com.vn",
"thanhtv11@viettel.com.vn",
"txthinh@viettel.com.vn",
"hunghs@viettel.com.vn",
"chinhnc@viettel.com.vn",
"anhth3@viettel.com.vn",
"thongplh@viettel.com.vn",
"tuantm12@viettel.com.vn",
"duynv7@viettel.com.vn",
"dutv1@viettel.com.vn",
"toannk86@viettel.com.vn",
"leduongtran@viettel.com.vn",
"sonlt2@viettel.com.vn",
"huongav@viettel.com.vn",
"sangnv1@viettel.com.vn",
"nghianq@viettel.com.vn",
"khiemvk@viettel.com.vn",
"huynx6@viettel.com.vn",
"hungnd61@viettel.com.vn",
"hoapv5@viettel.com.vn",
"vyhx@viettel.com.vn",
"duylbk@viettel.com.vn",
"yenltt@viettel.com.vn",
"thinhhv@viettel.com.vn",
"thanhlm1@viettel.com.vn",
"sonph@viettel.com.vn",
"phukhuong@viettel.com.vn",
"dungdv4@viettel.com.vn",
"datvt18@viettel.com.vn",
"anhnt425@viettel.com.vn",
"anhtt69@viettel.com.vn",
"tuannd1@viettel.com.vn",
"ducca@viettel.com.vn",
"phongbd1@viettel.com.vn",
"nguyentd2@viettel.com.vn",
"haunt1@viettel.com.vn",
"minhphuong@viettel.com.vn",
"longdh1@viettel.com.vn",
"taind5@viettel.com.vn",
"trunghn@viettel.com.vn",
"phuongdtt2@viettel.com.vn",
"hoangtq3@viettel.com.vn",
"philh1@viettel.com.vn",
"tienthanhvn@viettel.com.vn",
"trinhnh@viettel.com.vn",
"hoanglesi@viettel.com.vn",
"vubt@viettel.com.vn",
"ducthanh@viettel.com.vn",
"nguyenmanhthang@viettel.com.vn",
"taitd@viettel.com.vn",
"dphh@viettel.com.vn",
"thanhnk2@viettel.com.vn",
"chienpt2@viettel.com.vn",
"hieunt92@viettel.com.vn",
"nguyenhoang@viettel.com.vn",
"buiankhang@viettel.com.vn",
"hoctb@viettel.com.vn",
"luongnt2@viettel.com.vn",
"thainn2@viettel.com.vn",
"huycd@viettel.com.vn",
"liennth@viettel.com.vn",
"diepdautu@viettel.com.vn",
"hanhntk@viettel.com.vn",
"chungnd4@viettel.com.vn",
"vanvuln@viettel.com.vn",
"vuongtt1@viettel.com.vn",
"phamxuanha@viettel.com.vn",
"ddchung@viettel.com.vn",
"antq@viettel.com.vn",
"tuhc@viettel.com.vn",
"tudm@viettel.com.vn",
"dungnt48@viettel.com.vn",
"linhhx@viettel.com.vn",
"longnt37@viettel.com.vn",
"phink@viettel.com.vn",
"thint11@viettel.com.vn",
"tatns@viettel.com.vn",
"quoclx@viettel.com.vn",
"doanhdv3@viettel.com.vn",
"dantq@viettel.com.vn",
"tuva@viettel.com.vn",
"cuongna@viettel.com.vn",
"phuocdc@viettel.com.vn",
"mymobile-dn@viettel.com.vn",
"loihh@viettel.com.vn",
"dungntn5@viettel.com.vn",
"hunghx@viettel.com.vn",
"duypt@viettel.com.vn",
"hungld6@viettel.com.vn",
"tungnn@viettel.com.vn",
"nguyenhuugiang_mtd@viettel.com.vn",
"thanhvm@viettel.com.vn",
"vulh@viettel.com.vn",
"longnt16@viettel.com.vn",
"sonvd@viettel.com.vn",
"tinhnk@viettel.com.vn",
"hungnm6@viettel.com.vn",
"vinhdq5@viettel.com.vn",
"huytx2@viettel.com.vn",
"diemlv@viettel.com.vn",
"hangntl9@viettel.com.vn",
"huongdouble@viettel.com.vn",
"thanhlv4@viettel.com.vn",
"namth@viettel.com.vn",
"duongnd2@viettel.com.vn",
"tienvh@viettel.com.vn",
"quyetnh1@viettel.com.vn",
"trungtq@viettel.com.vn",
"phuongdn1@viettel.com.vn",
"dunght@viettel.com.vn",
"hienth@viettel.com.vn",
"dungnt18@viettel.com.vn",
"thehm@viettel.com.vn",
"nguyentq@viettel.com.vn",
"vuongtv@viettel.com.vn",
"thuonglv@viettel.com.vn",
"chieund@viettel.com.vn",
"quangnt@viettel.com.vn",
"tailm@viettel.com.vn",
"thanhhd1@viettel.com.vn",
"minhnh16@viettel.com.vn",
"quynhnt30@viettel.com.vn",
"vinhnt44@viettel.com.vn",
"thucdx@viettel.com.vn",
"hieunt9@viettel.com.vn",
"phongld2@viettel.com.vn",
"vietnq@viettel.com.vn",
"thuannv@viettel.com.vn",
"vinhpn@viettel.com.vn",
"trungtt@viettel.com.vn",
"tuyenvh1@viettel.com.vn",
"halm@viettel.com.vn",
"hieulq2@viettel.com.vn",
"vu_duy@viettel.com.vn",
"quyetnv5@viettel.com.vn",
"sonhb@viettel.com.vn"]
